// Copy every non-HTML file from site/ into public/ so Next serves them as
// static assets at their original URLs (/colors_and_type.css, /assets/...).
// HTML pages are served by the app router instead, which emulates nginx's
// `try_files $uri $uri.html $uri/` rule.
//
// Gated artifacts (see GATED below) are NOT copied to public/. Instead their
// bytes are embedded into a generated module so the gated route can serve them
// from the Worker after a session check — Next's file tracing doesn't bundle
// files read via runtime readFileSync, so embedding is required.
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));
const site = path.join(root, "..", "site");
const embeddedDocs = path.join(root, "..", "embedded-docs");
const pub = path.join(root, "..", "public");

// Paths under site/ that must NOT be public — they are served only by the
// gated download route after a session check (keep in sync with
// lib/accounts/gated.mjs GATED_PREFIXES).
const GATED = ["school/forensics/assets/"];
const isGated = (rel) => GATED.some((p) => rel.split(path.sep).join("/").startsWith(p));

rmSync(pub, { recursive: true, force: true });
mkdirSync(pub, { recursive: true });

let copied = 0;
let gated = 0;
function walk(rel) {
  for (const entry of readdirSync(path.join(site, rel), { withFileTypes: true })) {
    const relPath = path.join(rel, entry.name);
    const norm = relPath.startsWith("." + path.sep) ? relPath.slice(2) : relPath;
    if (entry.isDirectory()) {
      walk(relPath);
    } else if (entry.name.endsWith(".html")) {
      // HTML is served by the app router, not as a static asset.
    } else if (isGated(norm)) {
      gated += 1; // withheld from public; gated route serves it
    } else {
      mkdirSync(path.dirname(path.join(pub, relPath)), { recursive: true });
      cpSync(path.join(site, relPath), path.join(pub, relPath));
      copied += 1;
    }
  }
}
// Collect gated files to embed.
const gatedFiles = [];
function collectGated(rel) {
  for (const entry of readdirSync(path.join(site, rel), { withFileTypes: true })) {
    const relPath = path.join(rel, entry.name);
    const norm = relPath.startsWith("." + path.sep) ? relPath.slice(2) : relPath;
    const posix = norm.split(path.sep).join("/");
    if (entry.isDirectory()) collectGated(relPath);
    else if (isGated(posix)) gatedFiles.push(posix);
  }
}

walk(".");
collectGated(".");

let embeddedDocsFiles = 0;
if (existsSync(embeddedDocs)) {
  const stack = [""];
  while (stack.length) {
    const rel = stack.pop();
    for (const entry of readdirSync(path.join(embeddedDocs, rel), { withFileTypes: true })) {
      const relPath = rel ? path.join(rel, entry.name) : entry.name;
      const sourcePath = path.join(embeddedDocs, relPath);
      if (entry.isDirectory()) {
        stack.push(relPath);
        continue;
      }
      if (entry.name.endsWith(".html")) continue;
      const targetPath = path.join(pub, "doc", relPath);
      mkdirSync(path.dirname(targetPath), { recursive: true });
      cpSync(sourcePath, targetPath);
      embeddedDocsFiles += 1;
    }
  }
}

// Emit the embedded-content module (base64 keyed by posix relative path).
const entries = gatedFiles
  .sort()
  .map((rel) => {
    const b64 = readFileSync(path.join(site, rel)).toString("base64");
    return `  ${JSON.stringify(rel)}: ${JSON.stringify(b64)},`;
  })
  .join("\n");
const genPath = path.join(root, "..", "lib", "accounts", "gated-content.generated.mjs");
writeFileSync(
  genPath,
  `// AUTO-GENERATED by scripts/sync-public.mjs. Do not edit.\n` +
    `// Base64 contents of gated artifacts, embedded for runtime serving in the Worker.\n` +
    `export const GATED_CONTENT = {\n${entries}\n};\n`,
);

console.log(
  `sync-public: copied ${copied} site asset(s) + ${embeddedDocsFiles} embedded doc file(s) to public/; embedded ${gatedFiles.length} gated file(s)`,
);
